function datosAlgorithm(const,const1,sp,sp1,mp,mp1,numember,analisis,test,numember1,analisis1,test1,tol,iter,tol1,iter1,print,print1,sistem,algoritmo,sistem1,algoritmo1,coef,coef1,integrador,integrador1,gamma,beta,gamma1,beta1)
    
    % Obtener datos del estrato
    % Evaluación de datos y almacenamiento de valores numéricos
    
    restricion = const;
    alphasp = sp;
    alphamp = mp;
    numerador = numember;
    analisis = analisis;
    test = test;
    tol = tol;
    iter = iter;
    impresion = print;
    sistema = sistem;
    algorit = algoritmo;
    coef = coef;
    integrador = integrador;
    gamma = gamma;
    beta = beta;
    
    restricion1 = const1;
    alphasp1 = sp1;
    alphamp1 = mp1;
    numerador1 = numember1;
    analisis1 =analisis1;
    test1 = test1;
    tol1 = tol1;
    iter1 = iter1;
    impresion1 = print1;
    sistema1 = sistem1;
    algorit1 = algoritmo1;
    coef1 = coef1;
    integrador1 = integrador1;
    gamma1 = gamma1;
    beta1 = beta1;
    
    
    
    
    % Ruta de almacenamiento
    
    if isdeployed
       path_file = strcat(ctfroot,'\mat\mfbi_001.mat'); 
    else
       path_file = strcat(pwd,'\mat\mfbi_001.mat'); 
    end
    
    path_file = load(path_file,'path_proj','path_projF');
    path_proj = path_file.path_proj;
    path_projF = path_file.path_projF;
   
    
    % Almacenamiento de datos
    name_colum_alg = {'restricion',...
                  'alphasp',...
                  'alphamp',...
                  'numerador',...
                  'analisis',...
                  'test',...
                  'tol',...
                  'iter',...
                  'impresion',...
                  'sistema',...
                  'algorit',...
                  'coef',...
                  'integrador',...
                  'gamma',...
                  'beta',...
                  'restricion1',...
                  'alphasp1',...
                  'alphamp1',...
                  'numerador1',...
                  'analisis1',...
                  'test1',...
                  'tol1',...
                  'iter1',...
                  'impresion1',...
                  'sistema1',...
                  'algorit1',...
                  'coef1',...
                  'integrador1',...
                  'gamma1',...
                  'beta1'
                };   
    
   
    save(path_proj,name_colum_alg{:},'-append')
    
    
end
