function newMatFile(archivo,columna,graficos,tipo,sElemX,numLayers,motionStep,motionDT,...
    faconv,famp,grade,layerThick,rho,refShearModul,refBulkModul,uBulk,...
    frictionAng,e,vPerm,hPerm,Vs,waterTable,damp,rockDen,rockVS,contrac1,...
    contrac3,dilat1,dilat3,PTAng,cohesion,refPress,surf,pathmf,path_sis,...
    restricion,alphasp,alphamp,numerador,analisis,test,tol,iter,impresion,...
    sistema,algorit,coef,integrador,gamma,beta,restricion1,alphasp1,alphamp1,...
    numerador1,analisis1,test1,tol1,iter1,impresion1,sistema1,...
    algorit1,coef1,integrador1,gamma1,beta1)

    
    % Individuales
    waterTable_str  = num2str(waterTable);
    damp_str        = num2str(damp*100);
    rockDen_str     = num2str(rockDen);
    rockVS_str      = num2str(rockVS);
    
    % Por estrato
    grade_str       	= cellfun(@num2str,grade,'un',0);
    layerThick_str  	= cellfun(@num2str,layerThick,'un',0);
    rho_str         	= cellfun(@num2str,rho,'un',0);
    refShearModul_str   = cellfun(@num2str,refShearModul,'un',0);
    refBulkModul_str    = cellfun(@num2str,refBulkModul,'un',0);
    uBulk_str           = cellfun(@num2str,uBulk,'un',0);
    frictionAng_str     = cellfun(@num2str,frictionAng,'un',0);
    e_str               = cellfun(@num2str,e,'un',0);
    vPerm_str   		= cellfun(@num2str,vPerm,'un',0);
    hPerm_str   		= cellfun(@num2str,hPerm,'un',0);
    Vs_str      		= cellfun(@num2str,Vs,'un',0);
    contrac1_str  		= cellfun(@num2str,contrac1,'un',0);
    contrac3_str  		= cellfun(@num2str,contrac3,'un',0);
    dilat1_str    		= cellfun(@num2str,dilat1,'un',0);
    dilat3_str    		= cellfun(@num2str,dilat3,'un',0);
    PTAng_str     		= cellfun(@num2str,PTAng,'un',0);
    refPress_str		= cellfun(@num2str,refPress,'un',0);
	surf_str			= cellfun(@num2str,surf,'un',0);
	cohesion_str		= cellfun(@num2str,cohesion,'un',0);
    
	
	name_estrato = {'archivo',...
				  'columna',...
				  'graficos',...
				  'sElemX',...
                  'damp',...
                  'damp_str',...
				  'waterTable',...
				  'waterTable_str',...
                  'rockDen',...
                  'rockVS',...
                  'rockDen_str',...
                  'rockVS_str',...
                  'path_sis',...
                  'motionDT',...
                  'faconv',...
                  'famp',...
                  'motionStep',...
                  'restricion',...
                  'alphasp',...
                  'alphamp',...
                  'numerador',...
                  'analisis',...
                  'test',...
                  'tol',...
                  'iter',...
                  'impresion',...
                  'sistema',...
                  'algorit',...
                  'coef',...
                  'integrador',...
                  'gamma',...
                  'beta',...
                  'restricion1',...
                  'alphasp1',...
                  'alphamp1',...
                  'numerador1',...
                  'analisis1',...
                  'test1',...
                  'tol1',...
                  'iter1',...
                  'impresion1',...
                  'sistema1',...
                  'algorit1',...
                  'coef1',...
                  'integrador1',...
                  'gamma1',...
                  'beta1',...
                  'tipo',...
                  'grade',...
                  'layerThick',...
                  'rho',...
                  'refShearModul',...
                  'refBulkModul',...
                  'uBulk',...
                  'frictionAng',...               
                  'vPerm',...
                  'hPerm',...
                  'Vs',...
                  'refPress',...
                  'surf',...
                  'e',...
                  'contrac1',...
                  'contrac3',...
                  'dilat1',...
                  'dilat3',...
                  'PTAng',...
                  'cohesion',...
                  'grade_str',...
                  'layerThick_str',...
                  'rho_str',...
                  'refShearModul_str',...
                  'refBulkModul_str',...
                  'uBulk_str',...
                  'frictionAng_str',...            
                  'vPerm_str',...
                  'hPerm_str',...
                  'Vs_str',...
                  'refPress_str',...
                  'surf_str',...
                  'e_str',...
                  'contrac1_str',...
                  'contrac3_str',...
                  'dilat1_str',...
                  'dilat3_str',...
                  'PTAng_str',...
                  'cohesion_str',...
                  'numLayers'
              };   
    
% Almacenar proyecto
save(pathmf,name_estrato{:})
    
    