function newProj(path_proj,path_projF)
% Función para crear nuevo proyecto de OpenLiq

% Inicialización de variables

	archivo 		= 1;
	columna			= {};
	graficos		= 0;

    % geometria
    sElemX          = {};
    damp            = {};
    damp_str        = '';
	waterTable      = {};
	waterTable_str  = '';
    % roca
    rockDen         = {};
	rockVS          = {};
    rockDen_str     = '';
    rockVS_str      = '';
    % sismo
    path_sis = '';
    motionDT    = 0.005;
    faconv      = 9.81;
    famp        = 1;
    motionStep = {};
    % analisis
    restricion = 2;
    alphasp = 1e14;
    alphamp = 1e14;
    numerador = 2;
    analisis =1;
    test = 2;
    tol = 0.0001;
    iter = 100;
    impresion = 3;
    sistema = 3;
    algorit = 5;
    coef = 0;
    integrador = 1;
    gamma = 0.5;
    beta = 0.25;
    
    restricion1 = 2;
    alphasp1 = 1e16;
    alphamp1 = 1e16;
    numerador1 = 1;
    analisis1 =1;
    test1 = 2;
    tol1 = 0.009;
    iter1 = 200;
    impresion1 = 2;
    sistema1 = 3;
    algorit1 = 5;
    coef1 = 0;
    integrador1 = 1;
    gamma1 = 0.5;
    beta1 = 0.25;
    
    %estratos
    tipo            = {};
    grade           = {};
    layerThick      = {};
    rho             = {};
    refShearModul   = {};
    refBulkModul    = {};
    uBulk           = {};
    frictionAng     = {};
    Vs              = {};
    vPerm           = {};
    hPerm           = {};
    refPress        = {};
    surf            = {};
    e               = {};
    contrac1        = {};
    contrac3        = {};
    dilat1          = {};
    dilat3          = {};
    PTAng           = {};
    cohesion        = {};
    
	numLayers       = {};
    soilThick       = {};

    
    grade_str           = {};
    layerThick_str      = {};
    rho_str             = {};
    refShearModul_str   = {};
    refBulkModul_str    = {};
    uBulk_str           = {};
    frictionAng_str     = {};
    Vs_str              = {};
    vPerm_str           = {};
    hPerm_str           = {};
    refPress_str        = {};
    surf_str            = {};
    e_str               = {};    
    contrac1_str        = {};
    contrac3_str        = {};
    dilat1_str          = {};
    dilat3_str          = {};
    PTAng_str           = {};
    cohesion_str            = {};
    

    name_estrato = {'archivo',...
				  'columna',...
				  'graficos',...
				  'sElemX',...
                  'damp',...
                  'damp_str',...
				  'waterTable',...
				  'waterTable_str',...
                  'rockDen',...
                  'rockVS',...
                  'rockDen_str',...
                  'rockVS_str',...
                  'path_sis',...
                  'motionDT',...
                  'faconv',...
                  'famp',...
                  'motionStep',...
                  'restricion',...
                  'alphasp',...
                  'alphamp',...
                  'numerador',...
                  'analisis',...
                  'test',...
                  'tol',...
                  'iter',...
                  'impresion',...
                  'sistema',...
                  'algorit',...
                  'coef',...
                  'integrador',...
                  'gamma',...
                  'beta',...
                  'restricion1',...
                  'alphasp1',...
                  'alphamp1',...
                  'numerador1',...
                  'analisis1',...
                  'test1',...
                  'tol1',...
                  'iter1',...
                  'impresion1',...
                  'sistema1',...
                  'algorit1',...
                  'coef1',...
                  'integrador1',...
                  'gamma1',...
                  'beta1',...
                  'tipo',...
                  'grade',...
                  'layerThick',...
                  'rho',...
                  'refShearModul',...
                  'refBulkModul',...
                  'uBulk',...
                  'frictionAng',...               
                  'vPerm',...
                  'hPerm',...
                  'Vs',...
                  'refPress',...
                  'surf',...
                  'e',...
                  'contrac1',...
                  'contrac3',...
                  'dilat1',...
                  'dilat3',...
                  'PTAng',...
                  'cohesion',...
                  'grade_str',...
                  'layerThick_str',...
                  'rho_str',...
                  'refShearModul_str',...
                  'refBulkModul_str',...
                  'uBulk_str',...
                  'frictionAng_str',...            
                  'vPerm_str',...
                  'hPerm_str',...
                  'Vs_str',...
                  'refPress_str',...
                  'surf_str',...
                  'e_str',...
                  'contrac1_str',...
                  'contrac3_str',...
                  'dilat1_str',...
                  'dilat3_str',...
                  'PTAng_str',...
                  'cohesion_str',...
                  'numLayers',...
                  'soilThick'
                 };
	
% Almacenar proyecto
save(path_proj,name_estrato{:})

    path = strrep(path_projF,'\','/');

    %guardar path en archivo src_tcl
    if isdeployed
       path_path = strcat(ctfroot,'\src_tcl\path.txt'); 
    else
       path_path = strcat(pwd,'\src_tcl\path.txt'); 
    end
    archivo = fopen(path_path,'w');
    fprintf(archivo,'set pathmaster "%s" \n',path(1:end-1));
    fclose(archivo);
    
    %Crear carpeta de postproceso y preproceso
    path_pre = strcat(path_projF,'pre_proceso');
    path_post = strcat(path_projF,'post_proceso');
    
    mkdir(path_pre)
    mkdir(path_post)

end